wip

diff --git a/vagrant/ocp4-master b/vagrant/ocp4-master
--- a/vagrant/ocp4-master
+++ b/vagrant/ocp4-master
@@ -48,13 +48,13 @@ sshKey: |
 EOF
 echo -n "  " >>install-config.yaml
 ssh-keygen -y -f /root/.ssh/id_rsa >>install-config.yaml
-openshift-install create cluster --log-level=debug
-if [ $? -ne 0 ]; then
-  echo Failed to deploy Openshift
-  exit 1
-fi
+#openshift-install create cluster --log-level=debug
+#if [ $? -ne 0 ]; then
+#  echo Failed to deploy Openshift
+#  exit 1
+#fi
 mkdir /root/.kube
-cp /root/ocp4/auth/kubeconfig /root/.kube/config
+#cp /root/ocp4/auth/kubeconfig /root/.kube/config
 sg=$(cat terraform.tfstate | jq -r '.resources[] | select(.name==("worker") and .type==("aws_security_group")).instances[0].attributes.id')
 aws configure set default.region $aws_region
 aws ec2 authorize-security-group-ingress --group-id $sg --protocol tcp --port 17001-17022 --cidr 0.0.0.0/0
