Update licenses

diff --git a/scripts/licenses b/scripts/licenses
--- a/scripts/licenses
+++ b/scripts/licenses
@@ -1,3 +1,16 @@
+if [ -z "$licenses" ]; then
+  echo '$licenses is empty'
+  exit
+fi
+
+for i in $licenses; do
+  echo $i | grep -Eq '^[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}$'
+  if [ $? -ne 0 ]; then
+    echo "Licence '$i' is invalid"
+        exit
+  fi
+done
+
 for i in $licenses; do
   while ! kubectl exec -n kube-system -it $(kubectl get pods -n kube-system -lname=portworx --field-selector=status.phase=Running | tail -1 | cut -f 1 -d " ") -- /opt/pwx/bin/pxctl license activate --ep UAT $i; do
     sleep 1
