re-try on deployment delete failure
closes #407

closes #408

diff --git a/scripts/pds-petclinic b/scripts/pds-petclinic
--- a/scripts/pds-petclinic
+++ b/scripts/pds-petclinic
@@ -123,17 +123,17 @@ echo "PDS_NAMESPACE_ID=\"$PDS_NAMESPACE_ID\""
 echo "Renaming Deployment Target from kube-system uuid to $TGT_NAME"
 curl -s -X "PUT" "$PDS_ENDPOINT/deployment-targets/$PDS_DEPLOYMENT_TARGET_ID" -H "accept: application/json" -H "Authorization: Bearer $PDS_TOKEN" -H "Content-Type: application/json" -d "{ \"name\": \"$TGT_NAME\"}" > /dev/null
 
-DEPLOY_STAT=\$(curl -s -X "GET"   "$PDS_ENDPOINT/deployment-targets/$PDS_DEPLOYMENT_TARGET_ID"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN"  | jq -r '.status')
+DEPLOY_STAT=$(curl -s -X "GET" "$PDS_ENDPOINT/deployment-targets/$PDS_DEPLOYMENT_TARGET_ID"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN"  | jq -r '.status')
 
-[[ \$DEPLOY_STAT == "null" ]] && { echo "Error: Deployment Status empty. ";  exit 1; }
+[[ $DEPLOY_STAT == "null" ]] && { echo "Error: Deployment Status empty. ";  exit 1; }
 
 echo "Waiting for Deployment Target to become healthy"
 
-while [ "\$DEPLOY_STAT" != "healthy" ]; do
+while [ "$DEPLOY_STAT" != "healthy" ]; do
 	sleep 5
-	echo "Current State	\$DEPLOY_STAT	\$(date)"
-	DEPLOY_STAT=\$(curl -s -X "GET"   "$PDS_ENDPOINT/deployment-targets/$PDS_DEPLOYMENT_TARGET_ID"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN"  | jq -r '.status')
-	[[ \$DEPLOY_STAT == "null" ]] && { echo "Error: Deployment Status empty. ";  exit 1; }
+	echo "Current State	$DEPLOY_STAT	\$(date)"
+	DEPLOY_STAT=$(curl -s -X "GET"   "$PDS_ENDPOINT/deployment-targets/$PDS_DEPLOYMENT_TARGET_ID"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN"  | jq -r '.status')
+	[[ $DEPLOY_STAT == "null" ]] && { echo "Error: Deployment Status empty. ";  exit 1; }
 done
 
 echo "Creating Deployment"
@@ -181,17 +181,25 @@ echo \$OUTPUT | jq -r '.data[] | .name, .id'
 
 for i in \$(echo \$OUTPUT | jq -r '.data[].id'); do
   echo "removing backup schedule/target for \$i"
-  curl -s -X "PUT" "$PDS_ENDPOINT/deployments/\$i" -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN" -H "Content-Type: application/json" -d "{ \"scheduled_backup\": { \"backup_policy_id\": null, \"backup_target_id\": null} }"
+  curl -s -X "PUT" "$PDS_ENDPOINT/deployments/\$i" -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN" -H "Content-Type: application/json" -d "{ \"scheduled_backup\": { \"backup_policy_id\": null, \"backup_target_id\": null} }" >/dev/null
   
   echo "deleting existing backups"
-  BACKUPS=\"$(curl -s -X "GET" "$PDS_ENDPOINT/deployments/\$i/backups" -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN")
+  BACKUPS=\$(curl -s -X "GET" "$PDS_ENDPOINT/deployments/\$i/backups" -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN")
   for BAK in \$(echo \$BACKUPS | jq -r '.data[].id'); do
-    echo "deleting backup \$BAK"
+    echo "    deleting backup \$BAK"
     curl -s -X "DELETE"   "$PDS_ENDPOINT/backups/\$BAK" -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN"  
   done
 
-  echo "deleting \$i"
-  curl -s -X "DELETE"   "$PDS_ENDPOINT/deployments/\$i"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN" 
+  echo "deleting deployment \$i"
+  DELSTATUS=\$(curl -s -X "DELETE"   "$PDS_ENDPOINT/deployments/\$i"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN" | jq -r '.http_status')
+  
+  while [ ! -z "\${DELSTATUS}" ]; do
+    echo "deployment deletion failed with status \$DELSTATUS. Waiting for dependencies to be deleted. Re-try in 5sec"
+    echo "if this fails, check & delete existing backup jobs manually"
+    sleep 5
+	DELSTATUS=\$(curl -s -X "DELETE"   "$PDS_ENDPOINT/deployments/\$i"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN" | jq -r '.http_status')
+  done
+
 done
 
 echo "Deleting Namespace $PDS_NAMESPACE"
